"""Access Bank provider tests.

Every credential, key and token used here is generated by the test that uses
it. All HTTP is served by httpx.MockTransport. No test contacts the real bank.
"""
from __future__ import annotations

import ssl

import pytest

from app.providers.accessbank import (
    _MAX_DAYS,
    _MAX_PAGES,
    _PAGE_SIZE,
    _PATH_ACCOUNTS,
    _PATH_AUTHENTICATE,
    _PATH_CONFIG,
    _PATH_TRANSACTIONS,
    AccessBankError,
    _ssl_context,
)


def test_only_four_paths_are_declared():
    """The module may reach exactly four endpoints. Adding a fifth is a
    deliberate act that should break this test and get reviewed."""
    import app.providers.accessbank as mod

    paths = {v for k, v in vars(mod).items() if k.startswith("_PATH_")}
    assert paths == {
        "/api/config/",
        "/gateway/api/session-manager/session/authenticate",
        "/gateway/api/customer-detail/fetch-customer-account-details",
        "/gateway/api/query-transaction/transaction-history",
    }


def test_no_forbidden_capability_in_paths():
    """No transfer, payment, beneficiary or statement endpoint."""
    import app.providers.accessbank as mod

    joined = " ".join(v for k, v in vars(mod).items() if k.startswith("_PATH_"))
    for forbidden in ("transfer", "payment", "beneficiar", "statement", "cheque", "token-request"):
        assert forbidden not in joined.lower()


def test_ssl_context_verifies_and_loads_the_pinned_chain():
    ctx = _ssl_context()
    assert ctx.verify_mode == ssl.CERT_REQUIRED
    assert ctx.check_hostname is True
    # The pinned intermediate is loaded IN ADDITION to the system roots,
    # never instead of them — so the context carries strictly more CAs than
    # a default one. Comparing counts proves the addition without depending
    # on how many roots the host happens to ship.
    assert len(ctx.get_ca_certs()) > len(ssl.create_default_context().get_ca_certs())


def test_error_message_never_leaks_detail():
    err = AccessBankError("authenticate", "rejected")
    assert str(err) == "accessbank: authenticate failed (rejected)"
